-- PLAYERS TABLE

CREATE TABLE IF NOT EXISTS players (
	player_id INTEGER PRIMARY KEY AUTOINCREMENT,
	player TEXT NOT NULL,
	joined INTEGER NOT NULL
)

-- CHATS TABLE

CREATE TABLE IF NOT EXISTS chats (
	chat_id INTEGER PRIMARY KEY AUTOINCREMENT,
	player TEXT NOT NULL,
   	message TEXT NOT NULL,
	timestamp INTEGER NOT NULL
)

-- CHATS TABLE INDEXS

CREATE INDEX IF NOT EXISTS idx_chat_timestamp ON chats (timestamp)

-- NOTES TABLE

CREATE TABLE IF NOT EXISTS notes (
	note_id INTEGER PRIMARY KEY AUTOINCREMENT,
	player TEXT NOT NULL,
   	data TEXT NOT NULL,
	timestamp INTEGER NOT NULL
)

-- NOTES TABLE INDEXS

CREATE INDEX IF NOT EXISTS idx_note_timestamp ON notes (timestamp);

-- ACTIONS TABLE

CREATE TABLE IF NOT EXISTS actions (
	action_id INTEGER PRIMARY KEY AUTOINCREMENT,
	player TEXT NOT NULL,
   	action TEXT NOT NULL,
   	reason TEXT,
	timestamp INTEGER NOT NULL
)

-- ACTIONS TABLE INDEXES

CREATE INDEX IF NOT EXISTS idx_action_timestamp ON actions (timestamp);
CREATE INDEX IF NOT EXISTS idx_player_action ON actions (player, action);